// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBCMPsCGmqrhiK8Blbea-iKyvO5BZBTs',
    appId: '1:728155207662:web:9a3f7c7a735d2f9dd500ff',
    messagingSenderId: '728155207662',
    projectId: 'attendance-log-dc4a2',
    authDomain: 'attendance-log-dc4a2.firebaseapp.com',
    storageBucket: 'attendance-log-dc4a2.appspot.com',
    measurementId: 'G-ZQHFRW0DC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8TAqGu-Qe2vg3MMTusePwM83MP2jO7Xk',
    appId: '1:728155207662:android:f855880b497c71add500ff',
    messagingSenderId: '728155207662',
    projectId: 'attendance-log-dc4a2',
    storageBucket: 'attendance-log-dc4a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBMtHcoM-QmGE1f-ONsUhN3uTtO2_iNcE',
    appId: '1:728155207662:ios:aeed81acb7b4172fd500ff',
    messagingSenderId: '728155207662',
    projectId: 'attendance-log-dc4a2',
    storageBucket: 'attendance-log-dc4a2.appspot.com',
    iosClientId: '728155207662-7k3r5s9jk9ctfudc1c90ir7d8uqfanrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceLogWithFirebase',
  );
}
